### ISSUE TITLE
Could you explain / comment the coordinate calculations in BusLocation.m

### ISSUE THREAD

**Issue by Skrekkur** [addi/Straeto-iphone-app#1]
Currently looks like a whole lot of math ninja voodoo. And what kind of coordinates come from strætó in the first place?

**Comment by baldurh** [comment]
I guess the coordinates from Strætó are in the ISNET94 format and this is the goto code for converting it to something you can show on a map. This same code can be found in many different places on the web. You can find a JS one from these sites:

http://kort.samsyn.is/api/api/v2/Example/Example12.aspx
http://kort.samsyn.is/api/SiteWatch.aspx?v=2&key=Bus49fVdg

And then there is [isn2wgs](https://github.com/gudmundur/isn2wgs)

I'm not sure who can explain the code though :P

**Comment by addi** [comment]
Yeah what Baldur said, i found it in some js function somewhere and converted it.

**Comment by Skrekkur** [comment]
ok thanks :)
