### ISSUE TITLE
New feature: Bus routes

### ISSUE THREAD

**Issue by Skrekkur** [addi/Straeto-iphone-app#2]
I have been looking into showing bus routes along with bus stops. 
(Currently only have bus stops for a given route). 

I was wondering if you had any ideas of putting this in the UI. Should it be a seperate "tab" or perhaps a global option to display the paths of the selected buses. Although that is a bit trickier in implementation when busses share part of a path.

**Comment by Skrekkur** [comment]
What I am thinking for this is. 
1. Click on a bus (annotation) 
2. Along with where it is going it has a button
3. When you click that button it shows the route for the selected bus. 
4. From the top comes a selection menu to select which direction you want to see as well as option to hide/stop showing route

**Comment by baldurh** [comment]
Regarding point no. 4:
Does it really matter which direction you want to see when showing the route? I think the route is excactly the same for either direction except in reverse order.

I think you should just begin with having a global option and maybe having different colors for each route (if possible)
